### ISSUE TITLE
Remember the last search

### ISSUE THREAD

**Issue by benvium** [calvium/react-native-component-viewer#12]
During my component dev workflow, I find that if hot-reloading fails (which often happens) I need to type my search term again (or scroll the list down to where I was).

Would be good to save and restore from local storage:

- the last search term

OR 

- the last search term AND scroll position.
> Make sure that the app doesn't crash if the scroll position is off-screen

- Good to have an opt-out property `saveSearch={false}` just in case.

@pablocarrillo Any opinions? Any issue with using `AsyncStorage` directly for this?

**Comment by pablocarrillo** [comment]
scroll position could be fine although maybe buggy? I think search should be better as ideally will present the term at the top.

Async storage or should work just fine IMO. Using other methods like a specialised reducer may have a bigger impact in the overall app

**Comment by briancalvium** [comment]
FlatList now has scrollToIndex/Item methods now - I'm not sure if that would make it easier

**Comment by pablocarrillo** [comment]
One thing to take into account is that if we use the index (or the scroll position) when we add new components the user can be scrolled to a different place than the intended.
If we want to do something more advanced I will store the name of the last component tap on and search for that component and scroll there the next time we enter in the component viewer (instead of filtering with the search if we don't want to).

**Comment by benvium** [comment]
Thanks @pablocarrillo. I think I'll just ignore scroll position and just store the last filter typed in.
That way you can type 'MyComponent' once and each time you reload your results are right there.

**Comment by benvium** [comment]
Closed by #13
